module.exports = {
  mainContainer: {
    backgroundColor: '#F6F7F8',
  },
  secondContainer: {
    marginTop: 70,
    marginLeft: 16,
    marginRight: 16,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
  },
  thirdContainer: {
    marginTop: 20,
    marginLeft: 16,
    marginRight: 16,
    backgroundColor: '#E5E5E5',
    borderRadius: 8,
  },
  fourthContainer: {
    marginTop: 20,
    marginLeft: 16,
    marginRight: 16,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
  },
  fifthContainer: {
    marginTop: 40,
    marginLeft: 16,
    marginRight: 16,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
  },
  sixthContainer: {
    marginTop: 40,
    marginLeft: 16,
    marginRight: 16,
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
  },
  seventhContainer: {
    marginTop: 40,
    marginLeft: 16,
    marginRight: 16,
    marginBottom: 50,
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
  },
  image: {
    width: 180,
    height: 180,
    borderRadius: 100,
    marginTop: 40,
    marginBottom: 20,
  },
  name: {
    color: '#1F2A36',
    fontFamily: 'OpenSans-Bold',
    fontSize: 26,
    marginBottom: 13,
  },
  editText: {
    color: '#9EA0A5',
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 24,
    marginBottom: 20,
    textAlign: 'center',
  },
  jobType: {
    color: '#9EA0A5',
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginBottom: 20,
  },
  location: {
    color: '#9EA0A5',
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginBottom: 13,
  },
  buttonSave: {
    backgroundColor: '#5E50A1',
    paddingTop: 15,
    paddingBottom: 15,
    borderRadius: 4,
    marginBottom: 15,
  },
  buttonSaveText: {
    textAlign: 'center',
    fontFamily: 'OpenSans-Bold',
    fontSize: 18,
    color: '#FFFFFF',
  },
  buttonCancel: {
    backgroundColor: '#F6F7F8',
    paddingTop: 15,
    paddingBottom: 15,
    borderRadius: 4,
    borderColor: '#5E50A1',
    borderWidth: 1,
  },
  buttonCancelText: {
    textAlign: 'center',
    fontFamily: 'OpenSans-Bold',
    fontSize: 18,
    color: '#5E50A1',
  },
  buttonSetting: {
    backgroundColor: '#FFFFFF',
    paddingTop: 15,
    paddingBottom: 15,
    borderRadius: 4,
    borderColor: '#FBB017',
    borderWidth: 1,
  },
  buttonSettingText: {
    textAlign: 'center',
    fontFamily: 'OpenSans-Bold',
    fontSize: 18,
    color: '#FBB017',
  },
  buttonSkillSave: {
    backgroundColor: '#FBB017',
    borderRadius: 4,
    borderColor: '#FBB017',
    borderWidth: 1,
    marginLeft: 10,
    width: 100,
    height: 50,
  },
  buttonSkillSaveText: {
    textAlign: 'center',
    fontFamily: 'OpenSans-Bold',
    fontSize: 18,
    color: '#FFFFFF',
    marginTop: 10,
  },
  location: {
    color: '#9EA0A5',
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginBottom: 20,
    marginLeft: 10,
  },
  position: {
    color: '#1F2A36',
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginBottom: 20,
  },
  title: {
    color: '#1F2A36',
    fontFamily: 'OpenSans-Bold',
    fontSize: 20,
    paddingTop: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderColor: '#E2E5ED',
    marginBottom: 20,
  },
  label: {
    color: '#9EA0A5',
    fontFamily: 'OpenSans-Regular',
    fontSize: 14,
    marginBottom: 5,
  },
  form: {
    height: 50,
    borderColor: '#E2E5ED',
    fontFamily: 'OpenSans-Regular',
    paddingLeft: 15,
    fontSize: 16,
    borderWidth: 1,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
  },
  formSkill: {
    height: 50,
    borderColor: '#E2E5ED',
    fontFamily: 'OpenSans-Regular',
    paddingLeft: 15,
    width: 210,
    fontSize: 16,
    borderWidth: 1,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
  },
  formDescription: {
    height: 150,
    borderColor: '#E2E5ED',
    fontFamily: 'OpenSans-Regular',
    paddingLeft: 15,
    fontSize: 16,
    paddingBottom: 100,
    borderWidth: 1,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
  },
  applicationType: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    color: '#46505C',
    marginTop: 3,
  },
  uploadImageContainer: {
    paddingTop: 50,
    paddingBottom: 50,
    borderWidth: 5,
    borderStyle: 'dashed',
    borderRadius: 1,
    borderColor: '#E2E5ED',
  },
};
