module.exports = {
  mainContainer: {
    backgroundColor: '#F6F7F8',
  },
  secondContainer: {
    marginTop: 70,
    marginLeft: 16,
    marginRight: 16,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
  },
  thirdContainer: {
    marginTop: 20,
    marginBottom: 100,
    marginLeft: 16,
    marginRight: 16,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
  },
  image: {
    width: 180,
    height: 180,
    borderRadius: 100,
    marginTop: 40,
    marginBottom: 20,
  },
  name: {
    color: '#1F2A36',
    fontFamily: 'OpenSans-Bold',
    fontSize: 26,
    marginBottom: 13,
  },
  position: {
    color: '#1F2A36',
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginBottom: 13,
  },
  location: {
    color: '#9EA0A5',
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginBottom: 13,
  },
  talent: {
    color: '#9EA0A5',
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginBottom: 13,
  },
  about: {
    color: '#9EA0A5',
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginBottom: 30,
  },
  button: {
    backgroundColor: '#5E50A1',
    paddingTop: 15,
    paddingBottom: 15,
    borderRadius: 4,
    marginBottom: 28,
  },
  buttonText: {
    textAlign: 'center',
    fontFamily: 'OpenSans-Bold',
    fontSize: 16,
    color: '#FFFFFF',
  },
  skillTitle: {
    color: '#1F2A36',
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 18,
    marginBottom: 10,
  },
  social: {
    color: '#9EA0A5',
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    marginBottom: 20,
    marginLeft: 10,
  }
}
